# Generated by Django 6.0.2 on 2026-02-05 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drafting", "0001_initial"),
        ("transition_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="draftcontent",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="drafting.draft",
            ),
        ),
        migrations.AddField(
            model_name="draftfact",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facts",
                to="drafting.draft",
            ),
        ),
        migrations.AddField(
            model_name="draftlegalmapping",
            name="bns_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="transition_engine.legalsection",
            ),
        ),
        migrations.AddField(
            model_name="draftlegalmapping",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legal_mappings",
                to="drafting.draft",
            ),
        ),
        migrations.AddField(
            model_name="draftlegalmapping",
            name="ipc_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="transition_engine.legalsection",
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="draft_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="drafting.drafttype"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draftfact",
            unique_together={("draft", "key")},
        ),
    ]
