# Generated by Django 6.0.2 on 2026-02-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drafting", "0001_initial"),
        ("transition_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftLegalMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent", models.CharField(max_length=255)),
                ("drafting_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bns_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="transition_engine.legalsection",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_mappings",
                        to="drafting.draft",
                    ),
                ),
                (
                    "ipc_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="transition_engine.legalsection",
                    ),
                ),
            ],
        ),
    ]
