# Generated by Django 6.0.2 on 2026-02-04 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("act", models.CharField(max_length=20)),
                ("section_number", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SectionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent", models.CharField(max_length=255)),
                ("drafting_note", models.TextField(blank=True)),
                (
                    "bns_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bns_mappings",
                        to="transition_engine.legalsection",
                    ),
                ),
                (
                    "ipc_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipc_mappings",
                        to="transition_engine.legalsection",
                    ),
                ),
            ],
        ),
    ]
