# Generated by Django 6.0.2 on 2026-02-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("court", models.CharField(max_length=255)),
                ("case_title", models.CharField(max_length=500)),
                ("citation", models.CharField(max_length=255, unique=True)),
                ("judgment_date", models.DateField()),
                ("acts", models.JSONField()),
                ("sections", models.JSONField()),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JudgmentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("relevant_sections", models.JSONField()),
                ("legal_issue", models.CharField(max_length=255)),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="legal_rag.judgment",
                    ),
                ),
            ],
        ),
    ]
